enhancer_list: LNCaP/Candidate_Enhancer_List.bed
promoter_list: LNCaP/Candidate_Promoter_List.bed
features:
    DNase: LNCaP/data/USC20140207_DNase_LNCaP_24U.bam
    H3K4me3: LNCaP/data/Marcel_LNCaP_H3K4me3.bam
    CTCF: LNCaP/data/BGI20101108_LNCaP_CTCF.bam 
    H3K27ac: LNCaP/data/USC20130125_LNCaP_H3K27ac.bam
results_dir: LNCaP/results


